# Generated by Django 3.0.2 on 2020-05-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200202_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscategorie',
            name='image',
        ),
        migrations.AddField(
            model_name='categorie',
            name='mdi_icon_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='mdi_icon_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
