# Generated by Django 3.1.1 on 2020-09-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200928_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverpage',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
