# Generated by Django 3.1.1 on 2020-09-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200928_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtPage',
            fields=[
                ('serverpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.serverpage')),
                ('Comment', models.TextField(blank=True, default='')),
            ],
            bases=('news.serverpage',),
        ),
    ]
