# Generated by Django 3.0.2 on 2020-07-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200527_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysadminSubpages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Url', models.CharField(max_length=30)),
                ('mdi_icon_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
