# Generated by Django 3.1.1 on 2020-09-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_sysadminsubpages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=40)),
                ('needUser', models.BooleanField()),
                ('needDevAccess', models.BooleanField()),
                ('needHiddenAccess', models.BooleanField()),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='SysadminSubpages',
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('serverpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.serverpage')),
                ('template', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('data', models.JSONField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorie')),
            ],
            bases=('news.serverpage',),
        ),
        migrations.CreateModel(
            name='subWebPage',
            fields=[
                ('serverpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.serverpage')),
                ('data', models.JSONField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.webpage')),
            ],
            bases=('news.serverpage',),
        ),
    ]
