# Generated by Django 3.1.1 on 2020-09-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200928_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverpage',
            name='icon',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='serverpage',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serverpage',
            name='needDevAccess',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serverpage',
            name='needHiddenAccess',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serverpage',
            name='needUser',
            field=models.BooleanField(default=False),
        ),
    ]
