# Generated by Django 3.1.3 on 2020-11-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tsjtCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tsjtArticle',
            fields=[
                ('sitearticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.sitearticle')),
                ('image', models.ImageField(blank=True, upload_to='tsjt/ArticleImages/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsjt.tsjtcategorie')),
            ],
            bases=('common.sitearticle',),
        ),
    ]
