# Generated by Django 3.0.2 on 2020-07-30 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mesure')),
                ('server_room_temperature', models.FloatField(default=0.0)),
                ('server_room_humidity', models.FloatField(default=0.0)),
            ],
        ),
    ]
