# Generated by Django 3.0.2 on 2020-09-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeteoValue',
        ),
    ]
