# Generated by Django 6.0.3 on 2026-03-14 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(choices=[('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], default='v2c', max_length=3)),
                ('community', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('auth_protocol', models.CharField(blank=True, choices=[('MD5', 'MD5'), ('SHA', 'SHA')], max_length=10)),
                ('auth_password', models.CharField(blank=True, max_length=100)),
                ('priv_protocol', models.CharField(blank=True, choices=[('DES', 'DES'), ('AES', 'AES')], max_length=10)),
                ('priv_password', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'SNMP Credential',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('category', models.CharField(choices=[('server', 'Serveur'), ('router', 'Routeur'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('ap', "Point d'accès"), ('iot', 'IoT'), ('printer', 'Imprimante'), ('workstation', 'Poste de travail'), ('other', 'Autre')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne'), ('degraded', 'Dégradé'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='network.network')),
                ('snmp_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.snmpcredential')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
    ]
