# Generated by Django 6.0.3 on 2026-03-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='open_ports',
            field=models.JSONField(blank=True, default=list, help_text='List of open ports found during discovery'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne'), ('degraded', 'Dégradé'), ('unknown', 'Inconnu'), ('discovered', 'Découvert')], default='unknown', max_length=20),
        ),
    ]
