# Generated by Django 6.0.3 on 2026-03-14 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_seen_device_open_ports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(help_text='SNMP ifIndex')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Inconnu')], default='unknown', max_length=10)),
                ('speed', models.BigIntegerField(default=0, help_text='Vitesse en bps')),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('vlan', models.PositiveIntegerField(blank=True, null=True)),
                ('in_octets', models.BigIntegerField(default=0)),
                ('out_octets', models.BigIntegerField(default=0)),
                ('in_errors', models.BigIntegerField(default=0)),
                ('out_errors', models.BigIntegerField(default=0)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('connected_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_via', to='devices.device')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='devices.device')),
            ],
            options={
                'ordering': ['device', 'index'],
                'unique_together': {('device', 'index')},
            },
        ),
    ]
