# Generated by Django 6.0.3 on 2026-03-14 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_deviceport'),
        ('network', '0002_network_last_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('server', 'Serveur'), ('router', 'Routeur'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('ap', "Point d'accès"), ('iot', 'IoT'), ('printer', 'Imprimante'), ('workstation', 'Poste de travail'), ('camera', 'Caméra / Visiophone'), ('other', 'Autre'), ('unknown', 'Inconnu')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne'), ('failed', 'En erreur')], default='online', max_length=20),
        ),
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('connected', 'Connecté'), ('disconnected', 'Déconnecté')], max_length=15)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='devices.device')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_logs', to='network.network')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='devices_con_created_d4848c_idx'), models.Index(fields=['device', '-created_at'], name='devices_con_device__9d7a28_idx')],
            },
        ),
    ]
