# Generated by Django 6.0.3 on 2026-03-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_category_alter_device_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('server', 'Serveur'), ('network', 'Équipement réseau'), ('ap', "Point d'accès"), ('iot', 'IoT'), ('printer', 'Imprimante'), ('workstation', 'Poste de travail'), ('phone', 'Téléphone'), ('camera', 'Caméra / Visiophone'), ('other', 'Autre'), ('unknown', 'Inconnu')], default='unknown', max_length=20),
        ),
    ]
