# Generated by Django 5.2.17 on 2026-08-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_snmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='open_ports',
            field=models.JSONField(blank=True, default=list, help_text='Ports ouverts détectés lors de la découverte'),
        ),
    ]
