# Generated by Django 3.1.3 on 2020-12-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronecomponent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drone/compimg', verbose_name='Photo du composant'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drone/confimg', verbose_name='Photo de la configuration'),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='datalog',
            field=models.FileField(blank=True, upload_to='drone/datalog', verbose_name='lien vers le log du vol'),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='video',
            field=models.FileField(blank=True, upload_to='drone/videoflight', verbose_name='Vidéo du vol'),
        ),
    ]
