"""Fichier main.urls.py définissant les urls."""
from django.conf.urls.static import static
from django.conf import settings as main_settings
from django.urls import path
from .views import (
    accueil, a_propos, a_propos_cv, a_propos_publications,
    mes_projets, mes_projets_categorie, mes_projets_detail,
    archives, news, news_page,
    detailed_news, research, bricolage, bricolage_detail,
    monitoring, monitoring_machine_detail,
    machine_ping_sse, machine_ports_sse,
    monitoring_serveur_detail, serveur_check_sse,
    administration, admin_users,
    admin_projets, admin_projet_ajouter, admin_projet_modifier, admin_projet_supprimer,
    admin_projet_categorie_ajouter, admin_projet_categorie_modifier,
    admin_projet_categorie_supprimer,
    admin_bricolages, admin_bricolage_ajouter, admin_bricolage_modifier,
    admin_bricolage_supprimer,
    admin_services,
    admin_machine_ajouter, admin_machine_modifier, admin_machine_supprimer,
    admin_serveur_ajouter, admin_serveur_modifier, admin_serveur_supprimer,
    admin_service_categorie_ajouter, admin_service_categorie_modifier,
    admin_service_categorie_supprimer,
)


urlpatterns = [
    path("", accueil, name='accueil'),
    path('a-propos/', a_propos, name='a_propos'),
    path('a-propos/cv/', a_propos_cv, name='a_propos_cv'),
    path('a-propos/publications/', a_propos_publications, name='a_propos_publications'),
    path('mes-projets/', mes_projets, name='mes_projets'),
    path('mes-projets/categorie/<slug:slug>/', mes_projets_categorie, name='mes_projets_categorie'),
    path('mes-projets/projet/<slug:slug>/', mes_projets_detail, name='mes_projets_detail'),
    path('archives/', archives, name='archives'),
    path('archives/news/', news, name='archives_news'),
    path('archives/news/<int:n_page>', news_page, name='archives_news_page'),
    path('archives/article/<int:article_id>', detailed_news, name='detailed_news'),
    path('archives/research/', research, name='archives_research'),
    path('bricolage/', bricolage, name='bricolage'),
    path('bricolage/<slug:slug>/', bricolage_detail, name='bricolage_detail'),
    path('monitoring/', monitoring, name='monitoring'),
    path('monitoring/machine/<int:machine_id>/', monitoring_machine_detail, name='monitoring_machine_detail'),
    path('monitoring/machine/<int:machine_id>/ping/', machine_ping_sse, name='machine_ping_sse'),
    path('monitoring/machine/<int:machine_id>/ports/', machine_ports_sse, name='machine_ports_sse'),
    path('monitoring/serveur/<int:serveur_id>/', monitoring_serveur_detail, name='monitoring_serveur_detail'),
    path('monitoring/serveur/<int:serveur_id>/check/', serveur_check_sse, name='serveur_check_sse'),
    path('administration/', administration, name='administration'),
    path('administration/utilisateurs/', admin_users, name='admin_users'),
    path('administration/projets/', admin_projets, name='admin_projets'),
    path('administration/projets/ajouter/', admin_projet_ajouter, name='admin_projet_ajouter'),
    path('administration/projets/modifier/<int:projet_id>/', admin_projet_modifier, name='admin_projet_modifier'),
    path('administration/projets/supprimer/<int:projet_id>/', admin_projet_supprimer, name='admin_projet_supprimer'),
    path('administration/projets/categories/ajouter/', admin_projet_categorie_ajouter, name='admin_projet_categorie_ajouter'),
    path('administration/projets/categories/modifier/<int:categorie_id>/', admin_projet_categorie_modifier, name='admin_projet_categorie_modifier'),
    path('administration/projets/categories/supprimer/<int:categorie_id>/', admin_projet_categorie_supprimer, name='admin_projet_categorie_supprimer'),
    path('administration/bricolages/', admin_bricolages, name='admin_bricolages'),
    path('administration/bricolages/ajouter/', admin_bricolage_ajouter, name='admin_bricolage_ajouter'),
    path('administration/bricolages/modifier/<int:article_id>/', admin_bricolage_modifier, name='admin_bricolage_modifier'),
    path('administration/bricolages/supprimer/<int:article_id>/', admin_bricolage_supprimer, name='admin_bricolage_supprimer'),
    path('administration/services/', admin_services, name='admin_services'),
    path('administration/services/machines/ajouter/', admin_machine_ajouter, name='admin_machine_ajouter'),
    path('administration/services/machines/modifier/<int:machine_id>/', admin_machine_modifier, name='admin_machine_modifier'),
    path('administration/services/machines/supprimer/<int:machine_id>/', admin_machine_supprimer, name='admin_machine_supprimer'),
    path('administration/services/serveurs/ajouter/', admin_serveur_ajouter, name='admin_serveur_ajouter'),
    path('administration/services/serveurs/modifier/<int:serveur_id>/', admin_serveur_modifier, name='admin_serveur_modifier'),
    path('administration/services/serveurs/supprimer/<int:serveur_id>/', admin_serveur_supprimer, name='admin_serveur_supprimer'),
    path('administration/services/categories/ajouter/', admin_service_categorie_ajouter, name='admin_service_categorie_ajouter'),
    path('administration/services/categories/modifier/<int:categorie_id>/', admin_service_categorie_modifier, name='admin_service_categorie_modifier'),
    path('administration/services/categories/supprimer/<int:categorie_id>/', admin_service_categorie_supprimer, name='admin_service_categorie_supprimer'),
] + static(main_settings.MEDIA_URL, document_root=main_settings.MEDIA_ROOT)
