# Generated by Django 3.1.2 on 2020-10-29 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('contenu', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DroneComponentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('onBoard', models.BooleanField(verbose_name='Onboard component of field component')),
            ],
        ),
        migrations.CreateModel(
            name='DroneConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10)),
                ('nick_name', models.CharField(max_length=40, null=True)),
                ('components', models.TextField(null=True)),
                ('improvement_summary', models.TextField(null=True)),
                ('comments', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de realisation')),
            ],
            options={
                'verbose_name': 'Configuration Drone',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DroneFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de realisation')),
                ('name', models.CharField(max_length=40, null=True)),
                ('meteo', models.TextField(null=True)),
                ('summary', models.TextField()),
                ('comments', models.TextField()),
                ('drone_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.droneconfiguration')),
            ],
            options={
                'verbose_name': 'Vol de  Drone',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DroneComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('weight', models.FloatField(null=True)),
                ('datasheet', models.URLField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dronecomponentcategory')),
            ],
        ),
    ]
