# Generated by Django 3.1.1 on 2020-11-02 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20201101_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomments',
            options={'ordering': ['-date'], 'verbose_name': "Commentaire d'article"},
        ),
        migrations.AlterModelOptions(
            name='configurationcomments',
            options={'ordering': ['-date'], 'verbose_name': "Commentaire d'article"},
        ),
        migrations.AlterModelOptions(
            name='droneconfiguration',
            options={'ordering': ['-date'], 'verbose_name': 'Configuration Drone'},
        ),
        migrations.AlterModelOptions(
            name='flightcomments',
            options={'ordering': ['-date'], 'verbose_name': "Commentaire d'article"},
        ),
        migrations.RemoveField(
            model_name='dronecomponent',
            name='comments',
        ),
        migrations.AddField(
            model_name='dronecomponent',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='articlecomments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.article', verbose_name='Article lié'),
        ),
        migrations.AlterField(
            model_name='articlecomments',
            name='contenu',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Contenu du commentaire au format Markdown'),
        ),
        migrations.AlterField(
            model_name='configurationcomments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.droneconfiguration', verbose_name='Configuration de drone liée'),
        ),
        migrations.AlterField(
            model_name='configurationcomments',
            name='contenu',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Contenu du commentaire au format Markdown'),
        ),
        migrations.CreateModel(
            name='DroneComponentComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Contenu du commentaire au format Markdown')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('active', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.dronecomponent', verbose_name='Composant de drone lié')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur du commentaire')),
            ],
            options={
                'verbose_name': 'Commentaire de composant de drone',
                'ordering': ['-date'],
            },
        ),
    ]
