# Generated by Django 3.1.3 on 2020-11-02 20:40

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201102_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightcomments',
            options={'ordering': ['-date'], 'verbose_name': 'Commentaire de vol'},
        ),
        migrations.AddField(
            model_name='droneflight',
            name='datalog',
            field=models.FileField(blank=True, upload_to='datalog', verbose_name='lien vers le log du vol'),
        ),
        migrations.AddField(
            model_name='droneflight',
            name='video',
            field=models.FileField(blank=True, upload_to='videoflight', verbose_name='Vidéo du vol'),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='compimg', verbose_name='Photo du composant'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='Composants',
            field=models.ManyToManyField(to='main.DroneComponent', verbose_name='Composants du drone'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='confimg', verbose_name='Photo de la configuration'),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='drone_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.droneconfiguration', verbose_name='la configuration de drone utilise'),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='meteo',
            field=models.JSONField(blank=True, default=dict, verbose_name='Definition Météo'),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Titre du vol'),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='summary',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Résumé du vol et observations'),
        ),
    ]
