# Generated by Django 5.2.17 on 2026-08-10 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backgroundtask_triggered_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='log',
            field=models.TextField(blank=True, help_text="Journal d'exécution"),
        ),
        migrations.AlterField(
            model_name='backgroundtask',
            name='triggered_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur déclencheur (vide = automatique)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
