# Generated by Django 5.2.17 on 2026-08-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_sitearticle_id_alter_sitearticlecomment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitearticle',
            options={'ordering': ['-date'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='sitearticlecomment',
            options={'ordering': ['-date'], 'verbose_name': "commentaire d'article", 'verbose_name_plural': "commentaires d'article"},
        ),
        migrations.AlterField(
            model_name='sitearticlecomment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='commentaire approuvé'),
        ),
    ]
