# Generated by Django 6.0.3 on 2026-03-14 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_deviceport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('check_type', models.CharField(choices=[('icmp', 'Ping (ICMP)'), ('tcp', 'Port TCP'), ('http', 'HTTP(S)'), ('dns', 'DNS'), ('snmp', 'SNMP')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('interval', models.PositiveIntegerField(default=300, help_text='Intervalle en secondes')),
                ('timeout', models.PositiveIntegerField(default=10, help_text='Timeout en secondes')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration spécifique au type de check')),
                ('current_status', models.CharField(choices=[('up', 'OK'), ('down', 'En panne'), ('degraded', 'Dégradé'), ('unknown', 'Inconnu')], default='unknown', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='devices.device')),
            ],
            options={
                'ordering': ['device__hostname', 'check_type'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('up', 'OK'), ('down', 'En panne'), ('degraded', 'Dégradé')], max_length=10)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('monitoring_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.monitoringcheck')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['monitoring_check', '-created_at'], name='monitoring__monitor_f6be5a_idx')],
            },
        ),
    ]
