# Generated by Django 6.0.3 on 2026-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='status',
            field=models.CharField(choices=[('up', 'OK'), ('down', 'En panne'), ('failing', 'En erreur')], max_length=10),
        ),
        migrations.AlterField(
            model_name='monitoringcheck',
            name='current_status',
            field=models.CharField(choices=[('up', 'OK'), ('down', 'En panne'), ('failing', 'En erreur'), ('unknown', 'Inconnu')], default='unknown', max_length=10),
        ),
    ]
