# Generated by Django 3.1.3 on 2020-11-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatar', verbose_name='avatar')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
            ],
        ),
    ]
