# Generated by Django 4.2.11 on 2026-02-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_level",
            field=models.IntegerField(
                choices=[
                    (0, "Enregistré"),
                    (1, "Autorisé"),
                    (2, "Avancé"),
                    (3, "Administrateur"),
                ],
                default=0,
                verbose_name="niveau utilisateur",
            ),
        ),
    ]
