# Generated by Django 4.2.11 on 2026-02-20 20:14

from django.db import migrations


def populate_user_levels(apps, schema_editor):
    """Migre les groupes et flags existants vers le champ user_level."""
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("connector", "UserProfile")

    for user in User.objects.all():
        try:
            profile = UserProfile.objects.get(user=user)
        except UserProfile.DoesNotExist:
            profile = UserProfile.objects.create(user=user)

        if user.is_staff or user.is_superuser:
            profile.user_level = 3  # ADMINISTRATEUR
        elif user.groups.filter(name__in=["developper", "moderator"]).exists():
            profile.user_level = 2  # AVANCE
        elif user.groups.filter(name="validated").exists():
            profile.user_level = 1  # AUTORISE
        else:
            profile.user_level = 0  # ENREGISTRE
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0002_userprofile_user_level"),
    ]

    operations = [
        migrations.RunPython(populate_user_levels, migrations.RunPython.noop),
    ]
