# Generated by Django 5.2.17 on 2026-08-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_populate_user_levels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profil utilisateur', 'verbose_name_plural': 'profils utilisateurs'},
        ),
    ]
