# Generated by Django 3.1.3 on 2020-11-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mdi_icon_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mdi_icon_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('sitearticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.sitearticle')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.category', verbose_name="La catégorie de l'article")),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.subcategory', verbose_name='La sous-catégorie')),
            ],
            options={
                'verbose_name': 'www article',
                'ordering': ['-date'],
            },
            bases=('common.sitearticle',),
        ),
    ]
