# Generated by Django 3.1.3 on 2020-12-12 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('sitearticlecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.sitearticlecomment')),
            ],
            options={
                'verbose_name': "Commentaire d'article",
                'ordering': ['-date'],
            },
            bases=('common.sitearticlecomment',),
        ),
    ]
