# Generated by Django 4.2.11 on 2026-02-21 07:48

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0003_alter_category_id_alter_subcategory_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjetCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("mdi_icon_name", models.CharField(blank=True, max_length=30)),
                ("couleur", models.CharField(default="#5090C1", max_length=7)),
                ("ordre", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "catégorie de projet",
                "verbose_name_plural": "catégories de projet",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.AlterModelOptions(
            name="articlecomment",
            options={"ordering": ["-date"], "verbose_name": "Commentaire d’article"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Catégorie", "verbose_name_plural": "Catégories"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Sous-catégorie",
                "verbose_name_plural": "Sous-catégories",
            },
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("resume", models.CharField(max_length=300, verbose_name="Résumé")),
                (
                    "contenu",
                    markdownx.models.MarkdownxField(blank=True, verbose_name="Contenu"),
                ),
                (
                    "lien_externe",
                    models.URLField(blank=True, verbose_name="Lien externe"),
                ),
                ("mdi_icon_name", models.CharField(blank=True, max_length=30)),
                (
                    "couleur",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Couleur (surcharge)"
                    ),
                ),
                ("date_creation", models.DateField(verbose_name="Date de création")),
                ("actif", models.BooleanField(default=True)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projets",
                        to="www.projetcategorie",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "projet",
                "verbose_name_plural": "projets",
                "ordering": ["ordre", "-date_creation"],
            },
        ),
    ]
