# Generated by Django 4.2.11 on 2026-02-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0004_projetcategorie_alter_articlecomment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projetcategorie",
            name="couleur",
        ),
        migrations.AlterField(
            model_name="projet",
            name="couleur",
            field=models.CharField(
                default="#5090C1", max_length=7, verbose_name="Couleur"
            ),
        ),
    ]
