# Generated by Django 4.2.11 on 2026-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0005_remove_projetcategorie_couleur_alter_projet_couleur"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="icone_image",
            field=models.ImageField(
                blank=True, upload_to="projet_icones", verbose_name="Icône (image)"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="icone_url",
            field=models.URLField(blank=True, verbose_name="Icône (URL)"),
        ),
    ]
