# Generated by Django 4.2.11 on 2026-02-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0006_projet_icone_image_projet_icone_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="visibilite",
            field=models.IntegerField(
                choices=[
                    (-1, "Public"),
                    (0, "Enregistré"),
                    (1, "Autorisé"),
                    (2, "Avancé"),
                    (3, "Administrateur"),
                ],
                default=-1,
                verbose_name="Visibilité minimum",
            ),
        ),
    ]
