# Generated by Django 4.2.11 on 2026-02-21 14:29

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0007_projet_visibilite"),
    ]

    operations = [
        migrations.CreateModel(
            name="BricolageArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150, verbose_name="Titre")),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "contenu",
                    markdownx.models.MarkdownxField(
                        blank=True, default="", verbose_name="Contenu"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "article de bricolage",
                "verbose_name_plural": "articles de bricolage",
                "ordering": ["-date"],
            },
        ),
    ]
