# Generated by Django 4.2.11 on 2026-02-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0008_bricolagearticle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bricolagearticle",
            name="actif",
        ),
    ]
