# Generated by Django 4.2.11 on 2026-02-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0009_remove_bricolagearticle_actif"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("mdi_icon_name", models.CharField(blank=True, max_length=30)),
                ("ordre", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "catégorie de service",
                "verbose_name_plural": "catégories de service",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("url", models.URLField(verbose_name="URL du service")),
                ("mdi_icon_name", models.CharField(blank=True, max_length=30)),
                (
                    "icone_image",
                    models.ImageField(
                        blank=True,
                        upload_to="service_icones",
                        verbose_name="Icône (image)",
                    ),
                ),
                ("icone_url", models.URLField(blank=True, verbose_name="Icône (URL)")),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="www.servicecategorie",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ["categorie__ordre", "titre"],
            },
        ),
    ]
