# Generated by Django 4.2.11 on 2026-02-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0010_servicecategorie_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse_ip", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "ports_supplementaires",
                    models.CharField(
                        blank=True,
                        help_text="Ports ou plages à scanner en plus des ports courants (ex: 8080,9000-9100)",
                        max_length=200,
                        verbose_name="Ports supplémentaires",
                    ),
                ),
                (
                    "en_ligne",
                    models.BooleanField(default=False, verbose_name="En ligne"),
                ),
                ("derniere_verification", models.DateTimeField(blank=True, null=True)),
                ("derniere_vue_en_ligne", models.DateTimeField(blank=True, null=True)),
                (
                    "ports_ouverts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Ports ouverts"
                    ),
                ),
                (
                    "os_detecte",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="OS détecté"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="www.servicecategorie",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "machine",
                "verbose_name_plural": "machines",
                "ordering": ["categorie__ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Serveur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True, verbose_name="URL du service")),
                (
                    "adresse",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Port"
                    ),
                ),
                (
                    "en_ligne",
                    models.BooleanField(default=False, verbose_name="En ligne"),
                ),
                (
                    "reverse_proxy_ok",
                    models.BooleanField(default=False, verbose_name="Reverse proxy OK"),
                ),
                ("derniere_verification", models.DateTimeField(blank=True, null=True)),
                ("derniere_vue_en_ligne", models.DateTimeField(blank=True, null=True)),
                ("mdi_icon_name", models.CharField(blank=True, max_length=30)),
                (
                    "icone_image",
                    models.ImageField(
                        blank=True,
                        upload_to="service_icones",
                        verbose_name="Icône (image)",
                    ),
                ),
                ("icone_url", models.URLField(blank=True, verbose_name="Icône (URL)")),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serveurs",
                        to="www.servicecategorie",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "serveur",
                "verbose_name_plural": "serveurs",
                "ordering": ["categorie__ordre", "titre"],
            },
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
