# Generated by Django 4.2.11 on 2026-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0011_machine_serveur_delete_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="os_attendu",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="OS attendu"
            ),
        ),
    ]
