# Generated by Django 4.2.11 on 2026-02-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0012_machine_os_attendu"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="dernier_scan_os",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernier scan OS"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="dernier_scan_ports",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernier scan ports"
            ),
        ),
        migrations.AddField(
            model_name="serveur",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serveur",
            name="hostname",
            field=models.CharField(blank=True, max_length=200, verbose_name="Hostname"),
        ),
    ]
