# Generated by Django 4.2.11 on 2026-02-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0016_remove_machine_hostname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="alerte_ip",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Alerte IP"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Nom / Hostname"),
        ),
    ]
