# Generated by Django 3.1.3 on 2021-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantation',
            name='Harvested',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la récolte'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='Semis',
            field=models.DateField(blank=True, null=True, verbose_name='Date du semi sous abri'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='SemisTerre',
            field=models.DateField(blank=True, null=True, verbose_name='Date du semi en pleine terre'),
        ),
    ]
