# Generated by Django 3.1.3 on 2021-02-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potager', '0002_auto_20210203_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantation',
            name='CoordX',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='CoordY',
        ),
        migrations.AddField(
            model_name='plantation',
            name='Coordinates',
            field=models.JSONField(default={}, verbose_name='liste des coordonnées'),
        ),
    ]
