# Generated by Django 3.1.3 on 2021-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potager', '0004_auto_20210204_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='specifications',
            field=models.JSONField(default=dict, verbose_name='Informations supplémentaires'),
        ),
    ]
