# Generated by Django 3.1.3 on 2021-02-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potager', '0005_auto_20210204_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='stock_status',
            field=models.CharField(choices=[('ES', 'En Stock'), ('VI', 'Épuisé'), ('EA', "En cours d'approvision"), ('AC', 'A commander'), ('BV', 'Bientôt épuisé')], default='ES', max_length=2),
        ),
    ]
