# Generated by Django 3.1.3 on 2021-02-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potager', '0006_planttype_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='semis_status',
            field=models.CharField(choices=[('RY', 'Prêt à être planté'), ('PL', "Prévu d'être planté"), ('EG', 'Semé en Godet'), ('ET', 'Semé en terre'), ('RE', 'Récolté')], default='ET', max_length=2, verbose_name='Le statut de ce semis'),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='stock_status',
            field=models.CharField(choices=[('ES', 'En Stock'), ('VI', 'Épuisé'), ('EA', "En cours d'approvision"), ('AC', 'A commander'), ('BV', 'Bientôt épuisé')], default='ES', max_length=2, verbose_name='Le statut de cette semence.'),
        ),
    ]
