# Generated by Django 3.1.1 on 2020-10-30 09:37

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dronecomponent',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='droneconfiguration',
            name='components',
        ),
        migrations.RemoveField(
            model_name='droneconfiguration',
            name='improvement_summary',
        ),
        migrations.AddField(
            model_name='dronecomponent',
            name='comments',
            field=markdownx.models.MarkdownxField(null=True, verbose_name='Commentaires'),
        ),
        migrations.AddField(
            model_name='dronecomponent',
            name='specs',
            field=models.JSONField(null=True, verbose_name='Caractéristiques'),
        ),
        migrations.AddField(
            model_name='droneconfiguration',
            name='specs',
            field=models.JSONField(null=True, verbose_name='Caractéristiques'),
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(max_length=42, verbose_name="Auteur de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=markdownx.models.MarkdownxField(null=True, verbose_name="Contenu de l'article au format Markdown"),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name="slug de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=100, verbose_name="Titre de l'article"),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dronecomponentcategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='datasheet',
            field=models.URLField(null=True, verbose_name='Liens vers la datasheet'),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nom du composant'),
        ),
        migrations.AlterField(
            model_name='dronecomponentcategory',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='dronecomponentcategory',
            name='onBoard',
            field=models.BooleanField(verbose_name='Composant volant ou restant au sol'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='comments',
            field=markdownx.models.MarkdownxField(null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='nick_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Surnon de la version'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='version_number',
            field=models.CharField(max_length=10, verbose_name='Numéro de version'),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='comments',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='summary',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
