# Generated by Django 3.1.1 on 2020-10-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201030_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronecomponent',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo du composant'),
        ),
        migrations.AddField(
            model_name='droneconfiguration',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo de la configuration'),
        ),
    ]
