# Generated by Django 3.1.2 on 2020-10-31 20:28

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201031_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droneflight',
            options={'ordering': ['-date'], 'verbose_name': 'Vol de  Drone'},
        ),
        migrations.RemoveField(
            model_name='droneflight',
            name='comments',
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name="Contenu de l'article au format Markdown"),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='comments',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='datasheet',
            field=models.URLField(blank=True, null=True, verbose_name='Liens vers la datasheet'),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo du composant'),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='specs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Caractéristiques'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Surnon de la version'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo de la configuration'),
        ),
        migrations.AlterField(
            model_name='droneconfiguration',
            name='version_logiciel',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Version du logiciel du contrôleur de vol'),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='meteo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='droneflight',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
