# Generated by Django 6.0.8 on 2026-08-10 09:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('os_family', models.CharField(blank=True, help_text='linux | openwrt | windows', max_length=16)),
                ('ac_restores', models.CharField(blank=True, help_text='does it power itself back on?', max_length=16)),
                ('wol_known', models.CharField(blank=True, help_text='is Wake-on-LAN known to work?', max_length=16)),
                ('wake_order', models.PositiveIntegerField(default=0, help_text='0 = never woken automatically')),
                ('ssh_user', models.CharField(blank=True, max_length=32)),
                ('retired', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['wake_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('schema', models.PositiveIntegerField(default=1)),
                ('facts', models.JSONField(default=dict)),
                ('drift_status', models.CharField(default='unknown', max_length=20)),
                ('drift_count', models.PositiveIntegerField(default=0)),
                ('drift_changes', models.JSONField(default=list)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fleet.machine')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['machine', '-at'], name='fleet_repor_machine_4b5093_idx')],
                'constraints': [models.UniqueConstraint(fields=('machine', 'at'), name='fleet_report_unique_at')],
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=512)),
                ('remote', models.CharField(blank=True, max_length=256)),
                ('head', models.CharField(blank=True, max_length=64)),
                ('worktree', models.CharField(blank=True, help_text='clean | dirty', max_length=16)),
                ('behind', models.IntegerField(blank=True, help_text='commits behind the last known remote ref', null=True)),
                ('compose', models.CharField(default='-', max_length=16)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='fleet.machine')),
            ],
            options={
                'ordering': ['machine__name', 'project'],
                'constraints': [models.UniqueConstraint(fields=('machine', 'project', 'path'), name='fleet_stack_unique_per_path')],
            },
        ),
    ]
