# Generated by Django 5.2.17 on 2026-08-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='deploy_script',
            field=models.CharField(blank=True, help_text='script de déploiement rapporté par homelab-probe', max_length=128),
        ),
    ]
