# Generated by Django 6.0.3 on 2026-03-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='last_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
