# Generated by Django 5.2.17 on 2026-08-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_gatewaycredential_network_gateway_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaycredential',
            name='verify_ssl',
            field=models.BooleanField(default=False, help_text='Vérifier le certificat SSL (désactiver pour un auto-signé)'),
        ),
        migrations.AlterField(
            model_name='network',
            name='cidr',
            field=models.CharField(help_text='Notation CIDR, par ex. 192.168.1.0/24', max_length=43),
        ),
        migrations.AlterField(
            model_name='network',
            name='gateway_credential',
            field=models.ForeignKey(blank=True, help_text='Identifiants de la passerelle (OpenWrt)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.gatewaycredential'),
        ),
        migrations.AlterField(
            model_name='network',
            name='scan_interval',
            field=models.PositiveIntegerField(default=300, help_text='Intervalle de scan en secondes'),
        ),
    ]
